FROM node:10.7

ENV APP_ROOT /src

RUN mkdir ${APP_ROOT}
WORKDIR ${APP_ROOT}
ADD . ${APP_ROOT}

RUN npm install

# build args
ARG NUXT_ENV_BASE_URL
ENV NUXT_ENV_BASE_URL $NUXT_ENV_BASE_URL

ARG NUXT_ENV_API_URL
ENV NUXT_ENV_API_URL $NUXT_ENV_API_URL

ARG NUXT_ENV_ASSET_URL
ENV NUXT_ENV_ASSET_URL $NUXT_ENV_ASSET_URL

RUN npm run build

ENV HOST 0.0.0.0
EXPOSE 3000

CMD [ "npm", "run", "start" ]
